---
title: "TheHotspotProject"
author: "Siqi"
date: "12/6/2020"
output: html_document
---

```{r setwd}
#setwd("C:/859K_sl559/Script/Doc_R_markdown")
```

```{r, The table}
#The table for the refined maps
data <- read.csv("Table_2020Nov29.csv")
ReBy_DEM<- data$ReBy_DEM
ReBy_FC30<-data$ReBy_FC30
ReBy_DEMFC30<-data$ReBy_DEMFC30
DEMFC30_PA<-data$DEMFC30_PA
DEMFC30_B50<-data$DEMFC30_B50

#hist(ReBy_DEM)
par(mfrow=c(1,2))
hist(ReBy_DEM, main="Reby_DEM", xlab="Area_Ratio",ylab="Frequency",xlim=c(0,1),ylim=c(0,30),las=1, breaks=5)
#qqnorm(ReBy_DEM)
#qqline(ReBy_DEM)

#hist(ReBy_FC30)
hist(ReBy_FC30, main="ReBy_FC30", xlab="Area_Ratio",ylab="Frequency",xlim=c(0,1),ylim=c(0,30),las=1, breaks=5)
#qqnorm(ReBy_FC30)
#qqline(ReBy_FC30)

#hist(ReBy_DEMFC30)
hist(ReBy_DEMFC30, main="ReBy_DEMFC30", xlab="Area_Ratio",ylab="Frequency",xlim=c(0,1),ylim=c(0,30),las=1, breaks=5)
#qqnorm(ReBy_DEMFC30)
#qqline(ReBy_DEMFC30)

#hist(DEMFC30_B50)
hist(DEMFC30_B50, main="DEMFC30_B50", xlab="Area_Ratio",ylab="Frequency",xlim=c(0,1),ylim=c(0,30),las=1, breaks=5)
#qqnorm(DEMFC30_B50)
#qqline(DEMFC30_B50)

#hist(DEMFC30_PA)
hist(DEMFC30_PA, main="DEMFC30_PA", xlab="Area_Ratio",ylab="Frequency",xlim=c(0,1),ylim=c(0,50),las=1, breaks=5)
#qqnorm(DEMFC30_PA)
#qqline(DEMFC30_PA)

mean(ReBy_DEM)
sd(ReBy_DEM)

mean(ReBy_FC30)
sd(ReBy_FC30)

mean(ReBy_DEMFC30)
sd(ReBy_DEMFC30)

mean(DEMFC30_PA)
sd(DEMFC30_PA)

mean(DEMFC30_B50)
sd(DEMFC30_B50)
```

```{r, Forest Pactch Area}
Patch_data <- read.csv("RegionG2_rCRGrCndTC2000_tif_AttributeTable.csv")
Patch_Area <- Patch_data$P_Area_ha_Excel
range(Patch_Area)
#Categorize
Cat_Patch_Area<- cut(Patch_Area, breaks = c(100,1000,10000,100000,1000000,10000000,100000000), labels=c("100-1000","1000-10000","10000-100000","100000-1000000","1000000-10000000","1000000-100000000"))
Cat_Patch_Area[1:10]
summary(Cat_Patch_Area)
library("plyr")
Cat_count<-count(Cat_Patch_Area)
Cat_count
class(Cat_count)
Patch_Area<- Cat_count$x
Frequency <-Cat_count$freq

barplot(y$freq, names.arg =y$x)
library("ggplot2")
ggplot(data=Cat_count, aes(x=Patch_Area, y=Frequency)) +
  geom_bar(stat="identity", width=0.5)
#par(mfrow=c(1,2))


#hist(Patch_id, xlab="Patch_id",ylab="Frequency",xlim=c(0,40000),ylim=c(0,2),las=1, breaks=30)
#qqnorm(Patch_Area)
#qqline(Patch_Area)
```


```{r}
#plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
