# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_RasterToKML.py
# Created on: 2020-12-13 10:14:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
RcReBy_DEMFC30_Acanthoptila_nipalensis_tif = "RcReBy_DEMFC30_Acanthoptila_nipalensis.tif"
RcReBy_DEMFC30_Acanthoptila_nipalensis_kmz = "C:\\859K_sl559\\Scratch5\\RcReBy_DEMFC30_Acanthoptila_nipalensis.kmz"
import arcpy
arcpy.LayerToKML_conversion("RcReBy_DEMFC30_Acanthoptila_nipalensis.tif", "C:\\859K_sl559\\Scratch5\\RcReBy_DEMFC30_Acanthoptila_nipalensis.kmz", "0", "NO_COMPOSITE", "79.9999999998693 19.9999999998856 108.10000000081 33.999999999612", "2048", "96", "CLAMPED_TO_GROUND")

