# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_RegionGroup_test1.py
# Created on: 2020-12-04 13:09:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
arcpy.env.overwriteOutput = True
arcpy.env.workspace = "C:\\859K_sl559\\Scratch3"
arcpy.env.extent = "C:\\859K_sl559\\Scratch1\\BLraw_Stachyris_oglei.tif"

# Local variables:
BLraw_Stachyris_oglei_tif = "C:\\859K_sl559\\Scratch1\\BLraw_Stachyris_oglei.tif"
RegionG_S_oglei_test1_tif = "C:\\859K_sl559\\Scratch3\\RegionG_S_oglei_test1.tif"

# Process: Region Group
arcpy.gp.RegionGroup_sa(BLraw_Stachyris_oglei_tif, RegionG_S_oglei_test1_tif, "FOUR", "WITHIN", "ADD_LINK", "")

print (os.path.exists("C:\\859K_sl559\\Scratch3\\RegionG_S_oglei_test1.tif"))
