# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_ZonalStatisticAsTable.py
# Created on: 2020-12-06 17:18:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------


#################################################Successful, Accurate But very slow



# Import arcpy module
import arcpy


# Local variables:
RegionG_Ani_Projected_tif = "RegionG_Ani_Projected.tif"
ZonalTable_RegionG2_dbf = "C:\\859K_sl559\\Scratch3\\ZonalTable_RegionG2.dbf"

# Process: Zonal Geometry as Table
arcpy.gp.ZonalGeometryAsTable_sa(RegionG_Ani_Projected_tif, "Value", ZonalTable_RegionG2_dbf, "94.1231502405956")

#Check The documentaion standalone script; 
#It is a little bit complex, So I conducted this step in ArcMap(My PC)