# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_ProjectRaster.py
# Created on: 2020-12-06 15:33:04.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
BLraw_Acanthoptila_nipalensis_tif = "BLraw_Acanthoptila_nipalensis.tif"
BLraw_Acanthoptila_nipalensi_projected_tif = "C:\\859K_sl559\\Scratch3\\BLraw_Acanthoptila_nipalensi_projected.tif"

# Process: Project Raster
arcpy.ProjectRaster_management(BLraw_Acanthoptila_nipalensis_tif, BLraw_Acanthoptila_nipalensi_projected_tif, "PROJCS['World_Eckert_IV',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Eckert_IV'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],UNIT['Meter',1.0]]", "NEAREST", "94.1231502405956 94.1231502405956", "", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

