# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_MosaicToNewRaster_test.py
# Created on: 2021-01-04 21:38:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
utm_srtm_53_06_img = "utm_srtm_53_06.img"
utm_srtm_53_07_img = "utm_srtm_53_07.img"
srtm_53_08_img = "srtm_53_08.img"
DEM90m = "C:\\859K_sl559\\Data\\RawData\\DEM90m"
dem53test2_tif = "C:\\859K_sl559\\Data\\RawData\\DEM90m\\dem53test2.tif"

# Process: Mosaic To New Raster
arcpy.MosaicToNewRaster_management("utm_srtm_53_06.img;utm_srtm_53_07.img;srtm_53_08.img", DEM90m, "dem53test2.tif", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "16_BIT_SIGNED", "8.33333333333333E-04", "1", "MEAN", "FIRST")

