# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_Project.py
# Created on: 2020-12-06 14:53:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
RasterTPolygon_test_A1 = "RasterTPolygon_test_A1"
RasterTPolygon_test_A1_Projeted_shp = "C:\\859K_sl559\\Scratch3\\RasterTPolygon_test_A1_Projeted.shp"

# Process: Project
arcpy.Project_management(RasterTPolygon_test_A1, RasterTPolygon_test_A1_Projeted_shp, "PROJCS['World_Eckert_IV',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Eckert_IV'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],UNIT['Meter',1.0]]", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

