# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ARCMAP_SelectByLocation.py
# Created on: 2020-11-29 22:01:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
RegionOfInterest = "RegionOfInterest"
RegionOfInterest__4_ = RegionOfInterest
RegionOfInterest__3_ = "RegionOfInterest"

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(RegionOfInterest, "COMPLETELY_WITHIN", RegionOfInterest__3_, "", "NEW_SELECTION", "NOT_INVERT")

