# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_Merge.py
# Created on: 2020-12-11 19:47:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
# allow overwrite
arcpy.env.overwriteOutput = True

# Set the analysis environments
arcpy.env.workspace = "C:\\859K_sl559\\Data\\Dejure_PA"
arcpy.env.extent = "C:\\859K_sl559\\Data\\RegionOfInterest.shp"

#setting coordinate system
arcpy.env.outputCoordinateSystem = arcpy.SpatialReference("WGS 1984")


# Local variables:
WDPA_polygon_roiClip_shp = "WDPA_polygon_roiClip.shp"
China_NNR_roiClip_shp = "China_NNR_roiClip.shp"
China_locallevelPA_roiClip_shp = "China_locallevelPA_roiClip.shp"
WDPApolygon_ChinaPA_roiClip_Merge1_shp = "C:\\859K_sl559\\Data\\Dejure_PA\\WDPApolygon_ChinaPA_roiClip_Merge1.shp"

# Process: Merge
arcpy.Merge_management(["WDPA_polygon_roiClip.shp", "China_NNR_roiClip.shp", "China_locallevelPA_roiClip.shp"], 
                       "C:/output/Output.gdb/allroads", "", "ADD_SOURCE_INFO")

#Much easier in arcmap, so conducted this step in arcmap