# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_reclassify.py
# Created on: 2020-11-27 20:04:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
H_TC2000_ReC_tif = "H_TC2000_ReC.tif"
Reclass_tif1 = "C:\\Users\\sl559\\Documents\\ArcGIS\\Default.gdb\\Reclass_tif1"

# Process: Reclassify
arcpy.gp.Reclassify_sa(H_TC2000_ReC_tif, "Value", "0 0;1 1;NODATA 0", Reclass_tif1, "DATA")

