# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_ZonalStatisticAsTable.py
# Created on: 2020-12-06 17:18:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------


#################################################Notsuccessful



# Import arcpy module
import arcpy


# Local variables:
RegionG_Ani_Projected_tif = "RegionG_Ani_Projected.tif"
ZonalTable_RegionG1_dbf = "C:\\859K_sl559\\Scratch3\\ZonalTable_RegionG2.dbf"

# Process: Zonal Geometry as Table
arcpy.gp.ZonalGeometryAsTable_sa(RegionG_Ani_Projected_tif, "Value", ZonalTable_RegionG1_dbf, "94.1231502405956")

