# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_SelectByLocation.py
# Created on: 2020-12-01 15:13:24.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
All_Species = "All_Species"
All_Species__3_ = All_Species
RegionOfInterest = "RegionOfInterest"

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(All_Species, "COMPLETELY_WITHIN", RegionOfInterest, "", "NEW_SELECTION", "NOT_INVERT")

