# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ARCMAP_DISSOLVE.py
# Created on: 2020-11-29 21:51:01.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
All_Species_CopyFeatures = "All_Species_CopyFeatures"
All_Species_CopyFeatures_Dis = "C:\\Users\\sl559\\Documents\\ArcGIS\\Default.gdb\\All_Species_CopyFeatures_Dis"

# Process: Dissolve
arcpy.Dissolve_management(All_Species_CopyFeatures, All_Species_CopyFeatures_Dis, "SISID", "", "MULTI_PART", "DISSOLVE_LINES")

