# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_LayerToKML.py
# Created on: 2020-12-12 19:22:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.outputCoordinateSystem = arcpy.SpatialReference("WGS 1984")
arcpy.env.overwriteOutput = True
arcpy.env.workspace = "C:\\859K_sl559\\Scratch5"
#
composite = 'NO_COMPOSITE'
pixels = 2048
dpi = 96
clamped = 'CLAMPED_TO_GROUND'
# Local variables:
in_shp = "DEMFC30_Zoothera_salimalii.shp"
out_kmz = "DEMFC30_Zoothera_salimalii.kmz"

# Process: Layer To KML
arcpy.LayerToKML_conversion(in_shp, out_kmz,"0", composite, 
                                        '', pixels, dpi, clamped)

###Not succvessful in spyder