# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ArcMap_ZonalStatisticAsTable.py
# Created on: 2020-12-06 14:35:08.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
RasterTPolygon_test_A1 = "RasterTPolygon_test_A1"
BLraw_Acanthoptila_nipalensis_tif = "BLraw_Acanthoptila_nipalensis.tif"
ZonalSt_RasterT1 = "C:\\859K_sl559\\Scratch3\\ZonalSt_RasterT1"

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(RasterTPolygon_test_A1, "Id", BLraw_Acanthoptila_nipalensis_tif, ZonalSt_RasterT1, "DATA", "ALL")

