# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Step4.14_RasterToPolygon_RefionG2_rCRGrCndTC2000.py
# Created on: 2020-12-06 10:58:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
arcpy.env.overwriteOutput = True
arcpy.env.workspace = "C:\\859K_sl559\\Scratch3"
arcpy.env.extent = "C:\\859K_sl559\\Data\\RegionOfInterest.shp"
print (os.path.exists("C:\\859K_sl559\\Data\\RegionOfInterest.shp"))
print (os.path.exists("C:\\859K_sl559\\Scratch3\\RegionG2_rCRGrCndTC2000.tif"))


# Local variables:
RegionG2_rCRGrCndTC2000_tif = "C:\\859K_sl559\\Scratch3\\RegionG2_rCRGrCndTC2000.tif"
RasterTPolygon_RegionG2TC2000_shp = "C:\\859K_sl559\\Scratch3\\RasterTPolygon_RegionG2TC2000.shp"

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(RegionG2_rCRGrCndTC2000_tif, RasterTPolygon_RegionG2TC2000_shp, "NO_SIMPLIFY", "Value")

print (os.path.exists("C:\\859K_sl559\\Scratch3\\RasterTPolygon_RegionG2TC2000.shp"))