# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Step4.14_RasterToPolygon_RefionG2_rCRGrCndTC2000.py
# Created on: 2020-12-06 10:58:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
#import os
arcpy.env.overwriteOutput = True
arcpy.env.workspace = "C:\\859K_sl559\\Scratch3"
arcpy.env.extent = "C:\\859K_sl559\\Data\\RegionOfInterest.shp"
#print (os.path.exists("C:\\859K_sl559\\Scratch3\\ReclassNoData_H_TC2000.tif"))
#print (os.path.exists("C:\\859K_sl559\\Scratch3\\Reclass_RegionG_rCNTC2000.tif"))


# Local variables:
BLraw_Acanthoptila_nipalensis_tif = "BLraw_Acanthoptila_nipalensis.tif"
RasterTPolygon_test_A1_shp = "C:\\859K_sl559\\Scratch3\\RasterTPolygon_test_A1.shp"

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(BLraw_Acanthoptila_nipalensis_tif, RasterTPolygon_test_A1_shp, "NO_SIMPLIFY", "Value")

