# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Step4.17_EDistance_ReClass.py
# Created on: 2020-12-07 14:48:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.overwriteOutput = True
arcpy.env.workspace = "C:\\859K_sl559\\Scratch3"
arcpy.env.extent = "C:\\859K_sl559\\Data\\RegionOfInterest.shp"

# Local variables:
RegionG2_rCRGrCndTC2000_Proj_tif = "RegionG2_rCRGrCndTC2000_Proj.tif"
Reclass_RegionG2_rCRGrCndTC2000_Proj_tif = "C:\\859K_sl559\\Scratch3\\Reclass_RegionG2_rCRGrCndTC2000_Proj.tif"

# Process: Reclassify
#arcpy.gp.Reclassify_sa(EucDist_reC_RegionG2_TC2000_Proj_tif, "VALUE", "0 1;0 100 2;100 1000 3;1000 10000 4;10000 13604 5", Reclass_EucDist_reC_RegionG2_TC2000_Proj_tif, "DATA")
#arcpy.gp.Reclassify_sa(EucDist_reC_RegionG2_TC2000_Proj_tif, "VALUE", "0 NODATA;0 100 1;200 400 2;400 800 3;800 1600 4; 1600 3200 5; 3200 6400 6; 6400 12800 7; 12800 25600 8", Reclass_EucDist_reC_RegionG2_TC2000_Proj_tif, "DATA")
arcpy.gp.Reclassify_sa(RegionG2_rCRGrCndTC2000_Proj_tif, "Area_ha", "NODATA NODATA;100 1000 1;1000 10000 2;10000 100000 3;100000 1000000 4;1000000 10000000 5; 10000000 100000000 6", Reclass_RegionG2_rCRGrCndTC2000_Proj_tif, "DATA")

 