# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ARCMAP_con.py
# Created on: 2020-11-27 18:46:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Area_mask_DEM90m_final_tif = "Area_mask_DEM90m_final.tif"
Input_true_raster_or_constant_value = "1"
Input_false_raster_or_constant_value = "0"
Con_tif1 = "C:\\Users\\sl559\\Documents\\ArcGIS\\Default.gdb\\Con_tif1"

# Process: Con
arcpy.gp.Con_sa(Area_mask_DEM90m_final_tif, Input_true_raster_or_constant_value, Con_tif1, Input_false_raster_or_constant_value, "\"Value\" >= 500 AND \"Value\" <=3000")

