# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ARCMAP_layerTokml.py
# Created on: 2020-11-25 17:39:54.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Sp_Zoothera_salimalii = "Sp_Zoothera_salimalii"
Sp_Zoothera_salimalii_LayerT_kmz = "C:\\859K_sl559\\Scratch\\KMZ\\Sp_Zoothera_salimalii_LayerT.kmz"

# Process: Layer To KML
arcpy.LayerToKML_conversion(Sp_Zoothera_salimalii, Sp_Zoothera_salimalii_LayerT_kmz, "0", "NO_COMPOSITE", "DEFAULT", "1024", "96", "CLAMPED_TO_GROUND")

