# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Trying_RasterCalculator.py
# Created on: 2020-11-26 17:52:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------
# Import system modules
from arcpy.sa import *


# Set the analysis environments
arcpy.env.workspace = "C:\\859K_sl559\\Data"

# Set local variables
in_raster1 = "H_TC2000_ReC.tif"
in_raster2 = "SumPA_rC.tif"

# Excuate RasterCalculator(Minus) function
out_rc_minus_raster = RasterCalculator([in_raster1, in_raster2], ["x", "y"],
                                       "x-y", "", "FirstOf")

# Save the output
out_rc_minus_raster.save("C:\\859K_sl559\\Data\\raster_rc_minus.tif")

